/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module zvn_13 (
    input [3:0] a,
    input [3:0] b,
    input [3:0] addOut,
    input [5:0] alufn,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    z = !(addOut);
    v = (a[3+0-:1] & !addOut[3+0-:1] & (b[3+0-:1] ^ alufn[0+0-:1])) | (!a[3+0-:1] & addOut[3+0-:1] & !(b[3+0-:1] ^ alufn[0+0-:1]));
    n = addOut[3+0-:1];
  end
endmodule
